# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Developer Arthur
email: gogoke1@naver.com
description: > # this means to ignore newlines until "baseurl:"
  arthur developer blog page
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://choi-hye-min.github.io" # the base hostname & protocol for your site

#sidebar
default-image: arthur-profile.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: arthur

copyright:
   name: arthur
   link: 'https://choi-hye-min.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 12
paginate_path: /page:num/

# Tracker
analytics: UA-131362480-1

# Comments
disqus: yes
disqus-shortname: arthur-developer

#social
facebook: https://www.facebook.com/profile.php?id=100001745885436
#quora: http://quora.com/sharathdt
#twitter: http://twitter.com/@webjeda
github: https://choi-hye-min.github.io
email: gogoke1@naver.com

#facebook like box
fb-like-box: yes
fb-app-id:
fb-page-url: https://www.facebook.com/Arthur-developer-1573153896163865/
fb-page-title: Arthur-developer

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

category_dir: category/
tag_dir: tag/

# Custom Collection
collections:
  portfolio_post:
    output: true
    permalink: /:collection/:title

reloader:
    error_file: nil
    host: Jekyll::Site#config["host"]
    port: 35729

livereload: true